### ISSUE TITLE
Bubble chart from demo loads too long (or not at all) with 4 more bubbles

### ISSUE THREAD

**Issue by hahiserw** [phuonghuynh/bubble-chart#1]
I want to use your chart and I decided to start with demo. I need a lot of bubbles, so I started with adding 4 more to your demo and it stopped working. By this I mean, that Chrome (39.0.2171.95 m) wanted to kill the tab (but when I waited long enough it worked). Firefox (34.0.5) behaves similar.

I tried to debug it, but I went as far as running profile in Chrome developer tools. I noticed that function randomCirclesPositions took the most of the execution time. I suspect that $.each could be the culprit.

**Comment by phuonghuynh** [comment]
Thanks @hahiserw,

The purpose of `randomCirclesPositions` is to make sure no bubble can not be intersect on others, therefore output of this function is an array of positions of bubbles without overlay others.

There are 2 options to due with the issue (see the example)
    `intersectDelta`: Intersection between circles, in pixel
    `intersectInc`: Increment of intersectDelta, in pixel, the `randomCirclesPositions` will auto-add `intersectInc` if it can not find a position for a bubble 

In case you add 4 more on my demo, the function is infinity loop because it not find suitable positions for all of them. Therefore, I close this issue.

Hope this help
